### PR TITLE
Adding more support for structs in port functions

### PR DESCRIPTION
**Pull request by rjnw**

### CODE REVIEW

**Comment by sabauma** [comment]
Could we get some tests for these changes? We're getting dangerously close to our 80% cutoff.

**Comment by samth** [comment]
Can we get this merged?

**Comment by sabauma** [comment]
There are currently conflicts in this PR (probably due to how long it has been sitting around). I would like the tests in a956aeb to actually be run by the test suite.

**Comment by sabauma** [comment]
@rjnw, can you address these issues?

**Comment by rjnw** [comment]
I will take a look today.

**Pull request merged**
